import { StyleSheet,Dimensions } from 'react-native'

export const styles = StyleSheet.create({
    container:{
        flex:1,
        padding:15,
        flexDirection:'row',
        justifyContent:"space-around",
        flexWrap:"wrap",
        backgroundColor:'#4682B4'
    }, 
    inputAndroid:{
        backgroundColor:"white",
        fontSize:19,
        marginTop:15,
        width:Dimensions.get('window').width/2.2,
        height:41,
        color:'black' 
    },
    inputIOS:{
        borderWidth:1,
        borderColor:'silver',
        fontSize:19,
        marginTop:15,
        width:Dimensions.get('window').width/2.2,
        height:41,
        color:'black'
    },
    placeholder:{
        color:"black",
        fontStyle:'italic',
        fontWeight:'500'
    },
    title:{
        fontSize:35,
        fontWeight:"bold",
        borderBottomColor:'white',
        borderBottomWidth:3,
        backgroundColor:'#4682B4',
        width:'100%',
        textAlign:"center",
        color:'white'
    },
    filter:{
        width:200,
        height:50,
        backgroundColor:'#268ce6',
        marginTop:20,
        alignItems:'center',
        justifyContent:'center',
        borderRadius:10,
        borderColor:'white',
        borderWidth:4,
    },
    buttonText:{
        color:'white',
        fontSize:25,
        letterSpacing:3,
        fontWeight:'bold'
    }
})